### ISSUE TITLE
An error is reported when executing cress/test_scripts/test.en-x.st.sh script

### ISSUE THREAD

**Issue by hus18** [ictnlp/CRESS#1]
Traceback (most recent call last):
  File "/home/xxxx/anaconda3/envs/CRESS/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/home/xxxx/projects/CRESS/fairseq/fairseq_cli/generate.py", line 413, in cli_main
    main(args)
  File "/home/xxxx/projects/CRESS/fairseq/fairseq_cli/generate.py", line 50, in main
    return _main(cfg, sys.stdout)
  File "/home/xxxx/projects/CRESS/fairseq/fairseq_cli/generate.py", line 96, in _main
    models, saved_cfg = checkpoint_utils.load_model_ensemble(
  File "/home/xxxx/projects/CRESS/fairseq/fairseq/checkpoint_utils.py", line 374, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(
  File "/home/xxxx/projects/CRESS/fairseq/fairseq/checkpoint_utils.py", line 484, in load_model_ensemble_and_task
    model = task.build_model(cfg.model, from_checkpoint=True)
  File "/home/xxxx/projects/CRESS/cress/tasks/speech_to_text_modified.py", line 129, in build_model
    return super(SpeechToTextTaskModified, self).build_model(args, from_checkpoint)
  File "/home/xxxx/projects/CRESS/fairseq/fairseq/tasks/fairseq_task.py", line 691, in build_model
    model = models.build_model(args, self, from_checkpoint)
  File "/home/xxxx/projects/CRESS/fairseq/fairseq/models/__init__.py", line 106, in build_model
    return model.build_model(cfg, task)
  File "/home/xxxx/projects/CRESS/cress/models/hubert_transformer.py", line 233, in build_model
    encoder = cls.build_encoder(args, task, encoder_embed_tokens)
  File "/home/xxxx/projects/CRESS/cress/models/hubert_transformer.py", line 211, in build_encoder
    return HubertTransformerEncoder(args, task.target_dictionary, embed_tokens)
  File "/home/xxxx/projects/CRESS/cress/models/hubert_transformer.py", line 300, in __init__
    ckpt = checkpoint_utils.load_checkpoint_to_cpu(self.hubert_model_path)
  File "/home/xxxx/projects/CRESS/fairseq/fairseq/checkpoint_utils.py", line 321, in load_checkpoint_to_cpu
    with open(local_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/hubert_base_ls960.pt'

**Comment by Poeroz** [comment]
Please download the hubert-base model and put the file in the `checkpoints/` directory.

**Comment by hus18** [comment]
> Please download the hubert-base model and put the file in the `checkpoints/` directory.

solved, thank you
